### ISSUE TITLE
impossible de placer certains points ou d'utiliser le compas

### ISSUE THREAD

**Issue by rstephane** [Sesamath/sesalab#583]
Bonjour,
Nous rencontrons plusieurs comportements bizarres lorsque l'on se connecte sur labomep.sesamath.net/ ... avec mon fils. Nous utilisons FFX Quantum (tout est à jour, Mark 57, Adobe Flash player à jour - grrr pourquoi Adobe ??? :-) ). impossible d'utiliser le compas, parfois nous ne pouvons pas placer un point sur la grille, nous avons beau cliquer, les points ne se fixent pas à la grille, j'imagine que c'est du à Adobe .. mais que faire ?

Merci.

**Comment by dcaillibaud** [comment]
Difficile de répondre sans savoir de quel exercice il s'agit (ça n'a d'ailleurs rien à voir avec l'appli sesalab disponible ici sur github mais avec certaines ressources mises à disposition sur labomep.sesamath.net).

Pour l'usage de flash, certaines anciennes ressources sont en flash, mais rien n'oblige à les utiliser…

Pour l'utilisation du compas, je suppose que vous parlez de instrumenpoche, il y a des tutoriel dans les ressources en libre accès, et vous trouverez de l'aide sur http://instrumenpoche.sesamath.net/wiki/

**Comment by rstephane** [comment]
Bonjour,
je vous remercie pour vos réponses.
Nous allons regarder les tutos pour le compas.
Pour le "souci" en effet, il s'agit d'une professeur de collège (Nathalie BESACIER) qui nous a donné accès à ses exercices via https://labomep.sesamath.net/ et nous bloquons sur l'exercice 11 - séquence numéro 5 -.. 

Nous coinçons toujours sur le même exercice.
Que nous conseillez vous ? contacter la prof en direct ? 

Merci pour votre aide ! 

PS: nous aovns fait une video du souci , si vous le voulez je vous la poste sur wetransfert ou filesender de renater...

**Comment by dcaillibaud** [comment]
Bonjour,

S'il y a un problème sur un exercice de labomep, il faut effectivement contacter l'enseignant·e concerné·e (qui fera éventuellement un signalement dans labomep), car cela n'a rien à voir avec sesalab (ce dépôt github est dédié au développement de sesalab, utilisé dans labomep, mais sesalab ne fait que mettre en relation des élèves et des contenus. Lorsqu'une page internet s'affiche mal c'est en général celui qui publie la page qu'il faut contacter, rarement celui qui a développé le navigateur).

**Comment by rstephane** [comment]
Bonjour,
merci bcq pour ces explications et votre réactivité !
Je vais donc me rapprocher de l'enseignante.
Merci pour votre travail (open!).
Cdt.
