### ISSUE TITLE
Redresser les données Utilisateur et empêcher les cas de se reproduire

### ISSUE THREAD

**Issue by adrien-k** [Sesamath/sesalab#644]
Après analyse sur un dump de prod avec (très très très long, on peut faire un `--limit=100000` pour un premier aperçu)

```
./source/cli.js validation --entities=Utilisateur --dump
```

Voir les `TODO-DATA` sur l'entity Utilisateur

**Et les erreurs suivantes**
818 `Utilisateur#599e811eb17fd543fa605cc9 error: Utilisateur/mail Impossible de sauvegarder un utilisateur avec un mail invalide` (exemple: mail: 'barbara34660@hotmail .fr ')

149 `Utilisateur#59c2cb3d58f4e8040e3cc6e4 error: Utilisateur ne doit pas contenir de propriétés additionnelles : "passwordBis"`  -> à supprimer

1 `Utilisateur#59b636fba0517f28257bf924 error: Utilisateur ne doit pas contenir de propriétés additionnelles : "groupes"` -> à supprimer

6 `Utilisateur#59a90b5a46a1dd59a312b6a1 error: Utilisateur/newMail doit correspondre au format "email"` (exemple: newMail: 'Aurélie.Favre-bulle@rpn.ch')

-> sans doute passer une regexp sur tous ces mails (et empêcher de saisir un tel email dans l'interface utilisateur)

On a aussi pas mal d'utilisateurs (~9000) sans password ou avec un password null. Voir dans quels cas on l'autorise et dans quels cas on l'empêche.

**Comment by dcaillibaud** [comment]
Effectivement, on doit pouvoir commencer à faire un update pour corriger ces problèmes (virer newMail quand il est invalide, et probablement aussi les actions en attente pour le valider).

Pour le password, il doit toujours être une string non vide, pour les users qui viennent du sso et qui ne doivent pas pouvoir se logguer directement je met un pass arbitraire ("pas.de.login.direct" de mémoire) qui n'a aucune chance de permettre un login (car ne correspondant à aucun hash possible).
